// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKJLn0AP93bmZZYnuaO3BmLg7h7grp3pg',
    appId: '1:187278697686:web:cb78fdd223d43fd870d577',
    messagingSenderId: '187278697686',
    projectId: 'bid-game-1b17a',
    authDomain: 'bid-game-1b17a.firebaseapp.com',
    storageBucket: 'bid-game-1b17a.firebasestorage.app',
    measurementId: 'G-8VDCD439M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaGzmeX7uDxxge6PF_2wCCBGHxQpxi9Fs',
    appId: '1:187278697686:android:81a660cf583b3f7e70d577',
    messagingSenderId: '187278697686',
    projectId: 'bid-game-1b17a',
    storageBucket: 'bid-game-1b17a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZN3LfV67LnKERWbrmeZ26_6SBb2LyAc',
    appId: '1:187278697686:ios:43a4b53fa580da6970d577',
    messagingSenderId: '187278697686',
    projectId: 'bid-game-1b17a',
    storageBucket: 'bid-game-1b17a.firebasestorage.app',
    iosBundleId: 'com.bidgame.bidgames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZN3LfV67LnKERWbrmeZ26_6SBb2LyAc',
    appId: '1:187278697686:ios:43a4b53fa580da6970d577',
    messagingSenderId: '187278697686',
    projectId: 'bid-game-1b17a',
    storageBucket: 'bid-game-1b17a.firebasestorage.app',
    iosBundleId: 'com.bidgame.bidgames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKJLn0AP93bmZZYnuaO3BmLg7h7grp3pg',
    appId: '1:187278697686:web:a65ae5806b511b4470d577',
    messagingSenderId: '187278697686',
    projectId: 'bid-game-1b17a',
    authDomain: 'bid-game-1b17a.firebaseapp.com',
    storageBucket: 'bid-game-1b17a.firebasestorage.app',
    measurementId: 'G-DRZGCFJG3M',
  );
}
